### ISSUE TITLE
Add HEAD method support

### ISSUE THREAD

**Issue by Flameborn** [hacdias/caddy-filemanager#85]
According to RFC 2616, and [This](http://stackoverflow.com/questions/16578345/should-webdav-server-support-head-on-folders), a HEAD method is the same as a GET method, with the exception that HEAD has an empty message body in the response. Currently, this makes Caddy-FM incompatible with LFTP.
This method should be implemented for best compatibility.

**Comment by hacdias** [comment]
Sorry, but I'm using the official [Golang Webdav library](https://godoc.org/golang.org/x/net/webdav) and that's something I can't control 😞

**Comment by hacdias** [comment]
Although, I can "fake" a GET request and return only the headers in that case, making it compatible. What do you think?

**Comment by Flameborn** [comment]
I'm not sure if this has been raised with the [WebDav library](golang.org/x/net/webdav) developers, but I think having a fake GET method would be  the best option, until they provide a proper fix. Having said that, I perfectly understand if you do not wish to do this and wait for an official fix from the GoLang community.

**Comment by hacdias** [comment]
Curiously, i was checking webdav's source code and it does seem to support HEAD (check it: https://github.com/golang/net/blob/master/webdav/webdav.go#L52) so the problem must be mine. I'll see what I can do about this.

**Comment by hacdias** [comment]
What's the response you get if you do a HEAD request? @Flameborn

**Comment by Flameborn** [comment]
curl -I https://domain.com/webdav returns:
HTTP/1.1 405 Method Not Allowed
This is the same as what I get with LFTP.

**Comment by hacdias** [comment]
Oh but I think that GET doesn't work for collections on Webdav, not the way
it does for files:

----
9.4 GET, HEAD for Collections

The semantics of GET are unchanged when applied to a collection, since GET
is defined as, "retrieve whatever information (in the form of an entity) is
identified by the Request-URI" [RFC2616]. GET, when applied to a
collection, may return the contents of an "index.html" resource, a
human-readable view of the contents of the collection, or something else
altogether. Hence, it is possible that the result of a GET on a collection
will bear no correlation to the membership of the collection.

Similarly, since the definition of HEAD is a GET without a response message
body, the semantics of HEAD are unmodified when applied to collection
resources.
----

http://www.webdav.org/specs/rfc4918.html#rfc.section.9.4

So I'm not understanding the use case of GET for collections.

Does it work for files?

**Comment by hacdias** [comment]
Hello! You have any feedback related to this?

**Comment by Flameborn** [comment]
I am sorry, I was not able to reply earlier.

Theoretically, I believe that the commonly accepted way to do this is just to return a directory listing, either in XML or in any other form.
Interestingly, ‘curl -X “GET” https://user:pass@domain.com/dav/folder1' <https://user:pass@domain.com/dav/folder1'> returns ‘MEthod Not allowed’, similarly to a HEAD request.
Both GET and HEAD seem to work all right for files. The good news is that GoLang’s WebDav library is consistent, it does not allow either method for collections/directories, however LFTP does not seem to like this. The WebDav specifications do not really pinpoint a standard, but I believe these requests should not be denied. Maybe we could just regard a HEAD method as PROPFIND for a collection, to list that collection’s contents.

**Comment by hacdias** [comment]
What is the error you get on LFTP?

**Comment by Flameborn** [comment]
It tries to get a directory list, but fails with: 'Operation not supported: 405 Method Not Allowed (HEAD)’

**Comment by hacdias** [comment]
Is LFTP supposed to support Webdav? In their website it says "It supports FTP, HTTP, FISH, SFTP, HTTPS and FTPS protocols.". I know WebDav runs over HTTP, but WebDav has *different* specifications.

**Comment by Flameborn** [comment]
On the list of features page, it is marked as having partial webDav support. See here http://lftp.tech/features.html <http://lftp.tech/features.html>
While it does not support WebDav fully, it does work with other WebDav libraries, such as SabreDav (http://sabre.io/ <http://sabre.io/>), or FuguHub (http://fuguhub.com <http://fuguhub.com/>).

**Comment by hacdias** [comment]
Exactly, **partial** support. Since the `GET` method, for collections, doesn't have a defined behavior, that client should be using `PROPFIND` for WebDAV and not `GET`.

I don't know if I should emulate a `PROPFIND` request **or** render an HTML file with the listing in this case.

> GET, when applied to a collection, may return the contents of an "index.html" resource, a human-readable view of the contents of the collection, or something else altogether. [[Source]](http://www.webdav.org/specs/rfc4918.html#rfc.section.9.4)

So, since this is a bit unclear, I think I can emulate a `PROPFIND` request. Although, that will need a bit more processing because I need to check if the resource exists and if it is a directory. What do you think?

**Comment by Flameborn** [comment]
Personally, I vote for a PROPFIND, as it returns a standards-compliant directory listing.
